settings:
  metric_definition_dir: /etc/cloudscopes/metric_definition.d
  plugin_dir: /etc/cloudscopes/plugin.d
  default_sample_interval: 13
  provider: cloudwatch
  #key: AWS_KEY_ID
  #secret: AWS_SECRET_KEY
  region: us-west-2
  dimensions:
    InstanceId: "#{ec2.availability_zone}.#{ec2.instance_id}"
